#version: '3.4'
#services:
#  react-nginx-app:
#    stdin_open: true
#    build:
#      context: .
#      dockerfile: Dockerfile
#    expose:
#      - 8080
#    ports:
#      - 80:80
#    environment:
#      - CHOKIDAR_USEPOLLING=true
version: '3'

services:
  qr-react:
    image: react_app
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile